import type { Prisma } from '../generated/client'

export const incidentTypesSeedData: Prisma.IncidentTypeCreateManyInput[] = [
  {
    code: 20,
    name: 'Semana Receso Docente',
    description: 'Semana de Receso Docente(Res 250/9)',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 21,
    name: 'Ausencia Justificada',
    description: 'Ausencia Justificada',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 22,
    name: 'Ausencia Injustificada',
    description: 'Ausencia Injustificada',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Injustificada',
  },
  {
    code: 23,
    name: 'Licencia por Maternidad',
    description: 'Licencia por Maternidad',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Licencia de Maternidad',
  },
  {
    code: 3,
    name: 'Licencia deportiva y cultural',
    description: 'Licencia deportiva y cultural',
    deductible: null,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: false,
    sum: false,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 2,
    name: 'Citación Militar y Judicial',
    description: 'Citación Militar y Judicial',
    deductible: false,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: false,
    sum: false,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 25,
    name: 'Licencia sin sueldo pos Natal',
    description: 'Licencia sin Sueldo Pos Natal (Hasta 9 meses)',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Licencia sin sueldo',
  },
  {
    code: 26,
    name: 'Enfermedad 3 días o menos',
    description: 'Enfermedad 3 días o menos',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Enfermedad',
  },
  {
    code: 1,
    name: 'Movilización Agrícola, Salud, etc(interna)',
    description: 'Movilización Agrícola, Salud, etc(interna)',
    deductible: false,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: false,
    sum: false,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 12,
    name: 'Vacaciones',
    description: 'Vacaciones',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 27,
    name: 'Enfermedad más de 3 días ',
    description: 'Enfermedad más de 3 días ',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Enfermedad',
  },
  {
    code: 32,
    name: 'Lic.sin Sueldo',
    description: 'Licencia sin Sueldo (Problemas Personales)',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Licencia sin Sueldo',
  },
  {
    code: 35,
    name: 'Prestación Social',
    description: 'Prestación Social(Res 234/03)',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 36,
    name: 'Vacaciones Masivas',
    description: 'Vacaciones Masivas (descontar días)',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 40,
    name: 'Interrupción al 100%',
    description: 'Interrupción al 100%',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Suspensión Laboral',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Interrupciones',
  },
  {
    code: 50,
    name: 'No Pagar',
    description: 'No Pagar',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 15,
    name: 'Servicio Militar General',
    description: 'Servicio Militar General',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
  {
    code: 57,
    name: 'Trabajo a Distancia',
    description: 'Trabajo a Distancia',
    deductible: true,
    time_classification: '0.00',
    pay_for: 'Nada',
    avg: true,
    sum: true,
    incentive: false,
    classification: 'Autorizada',
  },
]
