import type { Prisma } from '../generated/client'

export const positionsSeedData: Prisma.PositionCreateManyInput[] = [
  {
    description: 'Técino General',
    category: 'T',
    level: 'TEC',
    group_escale: 'XI',
    code: 6999,
    total: 3610,
    scale: 3610,
  },
  {
    description: 'Especialista General',
    category: 'T',
    level: 'SUP',
    group_escale: 'XVI',
    code: 6998,
    total: 4410,
    scale: 4410,
  },
  {
    description: 'Especialista Superior',
    category: 'T',
    level: 'SUP',
    group_escale: 'XVII',
    code: 6997,
    total: 4610,
    scale: 4610,
  },
  {
    description: 'Asistente de Control',
    category: 'T',
    level: 'MED',
    group_escale: 'IX',
    code: 6588,
    total: 3110,
    scale: 3110,
  },
  {
    description: 'Técnico en Ciencias Informáticas',
    category: 'T',
    level: 'TEC',
    group_escale: 'XI',
    code: 6367,
    total: 3410,
    scale: 3410,
  },
  {
    description: 'Técnico "A" en Gestión de R.H',
    category: 'T',
    level: 'MED',
    group_escale: 'XI',
    code: 6330,
    total: 3410,
    scale: 3410,
  },
  {
    description: 'Técnico "A" en Gestión Económica',
    category: 'T',
    level: 'MED',
    group_escale: 'XI',
    code: 6206,
    total: 3410,
    scale: 3410,
  },
  {
    description: 'Subdirector',
    category: 'C',
    level: 'SUP',
    group_escale: 'XXIII',
    code: 32,
    total: 6060,
    scale: 6060,
  },
  {
    description: 'Director',
    category: 'C',
    level: 'SUP',
    group_escale: 'XXV',
    code: 12,
    total: 6610,
    scale: 6610,
  },
]
