export const director = {
     email: 'lesterr@uci.cu',
          first_name: 'Lester',
          middle_name:'',
          last_name: 'Rodríguez',
          second_last_name: 'Vallejo',
          record_number: '07646',
          organizations_codes: ["cdr","ujc", "ctc" ],
          position_code: 12,
          ci: '80020112465',
          address: 'CR. MALEZAS, Nro. E8, Apto. 5, Km: 7M, Localidad: RTO. BASE AEREA, Municipio: SANTA CLARA,VCL',
          parent1_name:'Juan',
          parent2_name:'Nery',
          tel:'286907',
          gender:'M',
          level:'SUP',
}

export const worker = {
    email: 'adrianbs@uci.cu',
    first_name: 'Adrian',
    middle_name:'',
    last_name: 'Balseiro',
    second_last_name: 'Sánchez',
    record_number: '23694',
    organizations_codes: ["cdr","ujc", "ctc" ],
    position_code: 6367,
    ci: '00011325455',
    address: '',
    parent1_name:'',
    parent2_name:'',
    tel:'',
    gender:'M',
    level:'MED',
}